# Generated by Django 4.1.4 on 2022-12-13 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiBlog', '0002_profesor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profesor',
        ),
        migrations.AddField(
            model_name='autor',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254),
        ),
        migrations.AddField(
            model_name='autor',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='autor',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
